# inspired by https://github.com/hypriot/rpi-node
sudo: required
services:
- docker
language: bash
env:
  #
before_install:
# terminate build if Dockerfile wasn't updated in one of the commits included in the changeset
- |
    echo "${TRAVIS_COMMIT_RANGE} -> ${TRAVIS_COMMIT_RANGE/.../..} (travis-ci/travis-ci#4596)"
    if ! git diff --name-only ${TRAVIS_COMMIT_RANGE/.../..} | grep -q Dockerfile
    then
      echo "Dockerfile was not updated, stopping build."
      exit
    fi
script:
# prepare QEMU
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- ./build.sh
- ./test.sh
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    ./push.sh
  fi
