# inspired by https://github.com/hypriot/rpi-node
sudo: required
services:
- docker
language: bash
env:
  #
script:
# prepare QEMU
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- ./build.sh
- ./test.sh
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    ./push.sh
  fi
