sudo: required
services:
- docker
language: bash
env:
  #
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- ./build.sh
# test image
#- ./test.sh $VERSION
# push image
#- >
#  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
#    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
#    ./push.sh $VERSION
#  fi
